# Generated by Django 3.0.5 on 2020-11-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_static_flight_directions_static_iata_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
